### ISSUE TITLE
FTEQuake AUR Package

### ISSUE THREAD

**Issue by FuZzledd** [mdeguzis/arch-aur-packages#1]
Hi, are you the maintainer of the FTE AUR package (https://aur.archlinux.org/packages/ftequake/)? I noticed it hasn't been updated in quite a while, and I was hoping that you could either update it, or possibly orphan it, as I wouldn't mind maintaining it (and the SVN version probably) myself. I was also going to add an Afterquake package, but it would probably be better to have plain FTE updated first :)

Thanks!

**Comment by mdeguzis** [comment]
If you are willing to take ownership, I can orphan it. I hope to get back to AUR packages, but with a new job starting soon and other priorities, tinkering with packaging has fallen by the wayside a bit. 

You can pick the package up now.

**Comment by FuZzledd** [comment]
Thanks very much!
